const assert=require('node:assert/strict');
require('./armx_rich_policy.js');
const game=new Chess(),before=game.fen();
const root=game.fastMoves().find(m=>m.from===game._sq('e2')&&m.to===game._sq('e4'));
const uniform=armxLearnedReplyResidual(game,{raw:root},new Float64Array(13),1);
assert.ok(uniform&&uniform.replies>1);
assert.ok(Math.abs(uniform.residual)<1e-10,'uniform prior must have no learned vote');
const weights=new Float64Array(13);weights[0]=1;weights[8]=2;
const frozen=Array.from(weights);
const learned=armxLearnedReplyResidual(game,{raw:root},weights,1);
assert.ok(Number.isFinite(learned.residual));
assert.ok(Math.abs(learned.residual)>1e-6,'nonuniform learned preferences must affect expectation');
assert.equal(game.fen(),before);assert.equal(game.historyStack.length,0);
assert.deepEqual(Array.from(weights),frozen);
for(const uci of ['e2e4','e7e5'])assert.ok(game.move({from:uci.slice(0,2),to:uci.slice(2,4)}));
const d4=game.fastMoves().find(m=>m.from===game._sq('d2')&&m.to===game._sq('d4'));
const current=game.fen();
assert.equal(armxLearnedReplyResidual(game,{raw:d4},weights,1),null,'unmodelled capture alternatives must block forecast');
assert.equal(game.fen(),current);assert.equal(game.historyStack.length,2);
console.log('ARMX_REPLY_FORECAST passed: zero uniform vote, learned-only residual, unmodelled reply exclusion, frozen weights and board purity');

const probeGame=new Chess(),probeFen=probeGame.fen();
const probeMove=probeGame.fastMoves().find(m=>m.from===probeGame._sq('e2')&&m.to===probeGame._sq('e4'));
const budget={limit:1,nodes:0};
assert.equal(armxLearnedReplyResidual(probeGame,{raw:probeMove},weights,1,budget),null,'incomplete tactical forecast has no value');
assert.equal(probeGame.fen(),probeFen);assert.equal(probeGame.historyStack.length,0);
assert.ok(budget.nodes>0&&budget.nodes<=budget.limit+1);
const observed=new Chess();
for(const uci of ['e2e4','e7e5','g1f3','b8c6','f1b5','a7a6','b5a4','g8f6','e1g1','f8e7','f1e1','b7b5','a4b3'])assert.ok(observed.move({from:uci.slice(0,2),to:uci.slice(2,4)}));
const observedBook=armxCausalSync(observed,observed.side);
observedBook.richQuiet.count=8;observedBook.richQuiet.qualitySum=2;
observedBook.richQuiet.projectionQualitySum=2;observedBook.richQuiet.qualityWeight=10;
const previewProfile=armxPreviewSyncProfile(observed,observed.side);
previewProfile.quietPolicy.qualitySum=-1;previewProfile.quietPolicy.qualityWeight=10;
const previewBudget=armxPreviewOpponentPolicy(observed,observed.side).searchBudget;
const reserved=armxFullOpponentPolicy(observed,observed.side);
assert.ok(reserved.forecastReserve>0);
assert.equal(reserved.searchBudget+reserved.forecastReserve,previewBudget,'tactical forecast cannot receive free nodes');
console.log('ARMX_REPLY_FORECAST_BUDGET passed: incomplete rejection, cleanup and reservation inside earned Preview budget');
