const assert=require('node:assert/strict');
require('./armx_finalists.js');
const row=armxCausalFreshRow();
assert.equal(armxCausalOutcomePrediction(row,'short',true),null);
assert.equal(armxCausalOutcomeValidated(row),false);
row.shortTreatedWeight=4;row.shortControlWeight=4;
row.shortTreatedImpact=2;row.shortControlImpact=-2;
const prediction=armxCausalOutcomePrediction(row,'short',true);
assert.equal(prediction.baseline,0);assert.equal(prediction.value,1/3);
for(let id=0;id<4;id++)armxCausalScoreOutcome(row,'short',prediction,.5,1,id);
assert.equal(armxCausalOutcomeValidated(row),true);
const oldWeight=row.outcomeQuality.short.weight;
armxCausalScoreOutcome(row,'short',prediction,.5,1,3);
assert.equal(row.outcomeQuality.short.weight,oldWeight);
assert.equal(row.outcomeQuality.short.observations.size,4);
for(let id=0;id<4;id++)armxCausalScoreOutcome(row,'long',prediction,-.5,1,id);
assert.equal(armxCausalOutcomeValidated(row),false,'mature contradictory horizon vetoes short result');
const future=armxCausalFreshRow();Object.assign(future,{shortTreatedWeight:4,shortControlWeight:4,shortTreatedImpact:2,shortControlImpact:-2});
const map=new Map([['quiet',future]]),book={pendingTrajectories:[]};
armxCausalQueueTrajectory(book,map,new Set(['quiet']),new Set(['quiet']),0,0);
const frozen=book.pendingTrajectories[0].shortPredictions.get('quiet');
assert.deepEqual(frozen,prediction);
future.shortTreatedImpact=-200;future.shortControlImpact=200;
armxCausalResolveTrajectories(book,2,180);
assert.ok(Math.abs(future.outcomeQuality.short.gain-(.25-(.5-1/3)**2)*armxCausalTrajectoryWeight(180))<1e-12,'later ledger changes cannot revise earlier forecast');
assert.equal(future.outcomeQuality.short.observations.size,1);
assert.equal(armxCausalOutcomeValidated(future),false,'single result cannot authorize causal vote');
assert.equal(future.outcomeQuality.long,undefined,'untrained long forecast cannot borrow short support');
const game=new Chess();for(const uci of ['g1f3','b8c6','b1c3','c6b8','f3g1','b8c6'])assert.ok(game.move({from:uci.slice(0,2),to:uci.slice(2,4)}));
const before=game.fen(),first=armxCausalSync(game,1);assert.equal(game.fen(),before);
game.reset();assert.notEqual(armxCausalSync(game,1),first);
console.log('ARMX_OUTCOME_VALIDATION passed: prior-only frozen forecasts, unique results, matched controls, delayed disagreement, reset and board purity');
const supported=armxCausalFreshRow();
Object.assign(supported,{treatedWeight:8,controlWeight:8,treatedImpact:4,controlImpact:-4,treatedImpactSq:2,controlImpactSq:2,shortTreatedWeight:8,shortControlWeight:8,shortTreatedImpact:4,shortControlImpact:-4,shortTreatedImpactSq:2,shortControlImpactSq:2,treatedObservations:new Set([0,1,2,3,4,5,6,7]),controlObservations:new Set([8,9,10,11,12,13,14,15])});
const supportedMap=new Map([['quiet',supported]]);
assert.equal(armxCausalTopEffects(supportedMap,['quiet']).length,1,'ordinary causal confidence fixture must be usable');
assert.equal(armxCausalTopEffects(supportedMap,['quiet'],4,null,true).length,0,'live effect selection must reject unvalidated rows');
const good=armxCausalOutcomePrediction(supported,'short',true);
for(let id=16;id<20;id++)armxCausalScoreOutcome(supported,'short',good,.5,1,id);
assert.equal(armxCausalTopEffects(supportedMap,['quiet'],4,null,true).length,1,'validated effect must reach the live selector');
console.log('ARMX_OUTCOME_SELECTION passed: validation enforced before selecting strongest effects');
