const fs=require('fs');
const engine=fs.readFileSync('StonefishChess.js','utf8');
const v3=fs.readFileSync('Stonefish_v3.js','utf8');
const harness=String.raw`
function seeded(seed){let x=seed>>>0;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296;};}
const CENTER=[27,28,35,36];
function devCount(g,s){const b=g.boardState,n=s===1?[1,6]:[57,62],bb=s===1?[2,5]:[58,61];let z=0;for(let q=0;q<64;q++){if(b[q]===s*2&&q!==n[0]&&q!==n[1])z++;if(b[q]===s*3&&q!==bb[0]&&q!==bb[1])z++;}return z;}
function undeveloped(g,s){const n=s===1?[1,6]:[57,62],b=s===1?[2,5]:[58,61];let z=0;for(const q of n)if(g.boardState[q]===s*2)z++;for(const q of b)if(g.boardState[q]===s*3)z++;return z;}
function isStartMinor(s,q,p){if(p===2)return s===1?(q===1||q===6):(q===57||q===62);if(p===3)return s===1?(q===2||q===5):(q===58||q===61);return false;}
function center(g,s){let z=0;for(const q of CENTER){const p=g.boardState[q];if(p&&(p>0?1:-1)===s)z+=2;if(g._isAttacked(q,s))z++;}return z;}
function kfree(g,s){const b=g.boardState,k=g.kingSq[s],f=k&7,r=k>>3,kp=b[k];let z=0;for(let i=0;i<SF_ALL_DIRS.length;i+=2){const nf=f+SF_ALL_DIRS[i],nr=r+SF_ALL_DIRS[i+1];if(nf<0||nf>7||nr<0||nr>7)continue;const t=nr*8+nf,x=b[t];if(x&&(x>0?1:-1)===s)continue;b[k]=0;b[t]=kp;const safe=!g._isAttacked(t,-s);b[k]=kp;b[t]=x;if(safe)z++;}return z;}
function kprot(g,s){const b=g.boardState,k=g.kingSq[s],f=k&7,r=k>>3,kp=b[k];let z=0;b[k]=0;for(let i=0;i<SF_ALL_DIRS.length;i+=2){const nf=f+SF_ALL_DIRS[i],nr=r+SF_ALL_DIRS[i+1];if(nf<0||nf>7||nr<0||nr>7)continue;const q=nr*8+nf,p=b[q];if(p&&(p>0?1:-1)===s)z+=Math.abs(p)===1?3:2;if(g._isAttacked(q,s))z++;}b[k]=kp;return z;}
function minorCentral(g,s){let z=0;for(let q=0;q<64;q++){const p=g.boardState[q];if(p!==s*2&&p!==s*3)continue;const f=q&7,r=q>>3;if(CENTER.includes(q))z+=4;else if(f>=2&&f<=5&&r>=2&&r<=5)z+=2;else if(!(f===0||f===7||r===0||r===7))z++;}return z;}
function rookAct(g,s){let z=0;for(let q=0;q<64;q++)if(g.boardState[q]===s*4){const f=q&7;let own=false;for(let r=0;r<8;r++)if(g.boardState[r*8+f]===s)own=true;if(!own)z+=2;}return z;}
function feature(g,m,c){const s0=g.side;if(c==='promotion')return m.promotion||0;if(c==='castleNow')return(m.flags&12)?1:0;if(c==='developNow')return g.fullmove<=12&&isStartMinor(s0,m.from,m.piece)?1:0;if(c==='centralPawnNow'){if(g.fullmove>8||m.piece!==1)return 0;const f=m.from&7,r=m.from>>3;return(f===3||f===4)&&((s0===1&&r===1)||(s0===-1&&r===6))?1:0;}if(c==='avoidWingPawn'){if(g.fullmove>8||m.piece!==1)return 1;const f=m.from&7;return(f===0||f===1||f===6||f===7)?0:1;}if(c==='avoidEarlyQueen')return g.fullmove<=9&&m.piece===5?0:1;if(c==='avoidEarlyRook')return g.fullmove<=10&&m.piece===4?0:1;if(c==='avoidEarlyKing')return g.fullmove<=10&&m.piece===6&&!(m.flags&12)?0:1;if(c==='avoidRepeatMinor'){if(g.fullmove>12||!(m.piece===2||m.piece===3)||undeveloped(g,s0)===0)return 1;return isStartMinor(s0,m.from,m.piece)?1:0;}if(c==='goodMinorSquare'){if(!(m.piece===2||m.piece===3))return 0;const f=m.to&7,r=m.to>>3;return(f>=2&&f<=5&&r>=2&&r<=5)?2:((f===0||f===7||r===0||r===7)?0:1);}if(c==='check')return g.fastGivesCheck(m)?1:0;if(c==='fiftyReset')return g.halfmove>=60&&(m.piece===1||m.captured)?1:0;g.fastApply(m);const s=-g.side;let z=0;if(c==='openingDevelop')z=g.fullmove<=13?devCount(g,s):0;else if(c==='queenDiscipline'){if(g.fullmove<=10){const h=s===1?3:59;z=g.boardState[h]===s*5?1:0;}}else if(c==='preserveCastle'){if(g.fullmove<=12){z=s===1?((g.castling&1?1:0)+(g.castling&2?1:0)):((g.castling&4?1:0)+(g.castling&8?1:0));}}else if(c==='repetitionAvoid')z=-(g.positionCounts.get(g.fastPositionKey())||0);else if(c==='mobility')z=g.fastMobility(s);else if(c==='pieceSupport')z=g._isAttacked(m.to,s)?1:0;else if(c==='kingFreedom')z=kfree(g,s);else if(c==='center')z=center(g,s);else if(c==='minorCentral')z=minorCentral(g,s);else if(c==='kingProtection')z=kprot(g,s);else if(c==='rookActivity')z=rookAct(g,s);g.fastUndo();return z;}
function choose3(g,r){const a=getStonefishV3BestRawMoves(g);return a.length?a[Math.floor(r()*a.length)]:null;}
function choose4(g,r,cfg){let a=getStonefishV3BestRawMoves(g).slice();if(!a.length)return null;for(const c of cfg.order){if(a.length<=1)break;let best=-Infinity,S=[];for(let i=0;i<a.length;i++){const z=feature(g,a[i],c);S[i]=z;if(z>best)best=z;}a=a.filter((_,i)=>S[i]===best);}return a[Math.floor(r()*a.length)];}
function draw(g){return g.halfmove>=100||g._insufficientMaterial()||(g.positionCounts.get(g.fastPositionKey())||0)>=3;}
function play(cfg,n,max=500){const g=new Chess(),vw=(n&1)===0,r3=seeded(0x9e3779b9^(n*0x45d9f3b)),r4=seeded(0x85ebca6b^(n*0x27d4eb2d));for(let p=0;p<max;p++){const vt=(g.turn()==='w')===vw,m=vt?choose4(g,r4,cfg):choose3(g,r3);if(!m){if(!g.in_check())return'D';const ww=g.turn()==='b';return ww===vw?'W':'L';}g._applyRaw(m,true);if(draw(g))return'D';}return'D';}
function test(cfg,n,start){let W=0,L=0,D=0;for(let i=0;i<n;i++){const r=play(cfg,start+i);if(r==='W')W++;else if(r==='L')L++;else D++;}return{W,L,D,games:n,score:W-5*L+.01*D};}
function rank(a,b){return b.r.score-a.r.score||a.r.L-b.r.L||b.r.W-a.r.W;}
const tail=['repetitionAvoid','fiftyReset','mobility','pieceSupport','kingFreedom','center','minorCentral','kingProtection','rookActivity','check'];
const opens=['castleNow','developNow','centralPawnNow','avoidRepeatMinor','avoidEarlyQueen','avoidEarlyRook','avoidEarlyKing','avoidWingPawn','preserveCastle','openingDevelop','queenDiscipline','goodMinorSquare'];
const C=[];let id=0;function add(o){C.push({name:'o'+id++,order:['promotion',...o,...tail]});}
add(['castleNow','developNow','centralPawnNow','avoidRepeatMinor','avoidEarlyQueen','avoidEarlyKing','avoidEarlyRook','avoidWingPawn','preserveCastle','queenDiscipline','goodMinorSquare','openingDevelop']);
add(['centralPawnNow','developNow','castleNow','avoidRepeatMinor','avoidEarlyQueen','avoidEarlyKing','avoidEarlyRook','avoidWingPawn','preserveCastle','queenDiscipline','goodMinorSquare','openingDevelop']);
add(['developNow','centralPawnNow','castleNow','avoidRepeatMinor','avoidEarlyQueen','avoidEarlyKing','avoidEarlyRook','avoidWingPawn','preserveCastle','queenDiscipline','goodMinorSquare','openingDevelop']);
add(['castleNow','centralPawnNow','developNow','avoidRepeatMinor','preserveCastle','avoidEarlyQueen','avoidEarlyKing','avoidEarlyRook','avoidWingPawn','queenDiscipline','goodMinorSquare','openingDevelop']);
const R=seeded(0x27182818);for(let i=0;i<70;i++){let a=opens.slice();for(let j=a.length-1;j>0;j--){const k=Math.floor(R()*(j+1));[a[j],a[k]]=[a[k],a[j]];}add(a);}
console.log('OPENING SCREEN',C.length,'x 12');const s=C.map(cfg=>({cfg,r:test(cfg,12,0)})).sort(rank);for(const x of s.slice(0,15))console.log(x.cfg.name,x.cfg.order.join('>'),x.r);
console.log('CONFIRM top 12 x 40');const c=s.slice(0,12).map(x=>({cfg:x.cfg,r:test(x.cfg,40,2100)})).sort(rank);for(const x of c)console.log(x.cfg.name,x.cfg.order.join('>'),x.r);
console.log('FINAL top 5 x 100');const f=c.slice(0,5).map(x=>({cfg:x.cfg,r:test(x.cfg,100,9000)})).sort(rank);for(const x of f)console.log('FINAL',x.cfg.name,x.cfg.order.join('>'),x.r);console.log('WINNER',JSON.stringify(f[0].cfg),f[0].r);
`;
new Function(engine+'\n'+v3+'\n'+harness)();
